### ISSUE TITLE
Improve note.html and users.html

### ISSUE THREAD

**Issue by phteffe** [Coppeloons/NoteShare#60]
Right now our note.html and users.html contains just the basics, would be good to flesh them out and have them working.

### Todo:

- [ ] users: All logged in have access to this one
- [ ] users: userRepo.findAll() when only returning name and username?
- [ ] notes: Admin role to see all notes. Logged in to see all notes with editor role
- [ ] note: Click on the title to go to this endpoint
- [ ] noteByUser: Role admin to access all users notes
- [x] user: Remove
- [x] note: Change id to note title
- [x] userByNote: Remove

Checked lines are added in the linked PR (https://github.com/Coppeloons/NoteShare/pull/67)
