### ISSUE TITLE
Update NoteController.java

### ISSUE THREAD

**Issue by jLereback** [Coppeloons/NoteShare#68]
### Todo:
- [ ] addNote: Ability to write username and not ID for the user
- [ ] getNote: Admin role to see all notes
- [ ] getAllNotes: Admin role to see all notes
- [ ] deleteNote: Users can't remove others notes
- [ ] updateText: Admin role to edit all notes. Logged in to edit notes with editor role
- [x] Logged in can only see their own notes
- [x] updateNote: Remove users in method to prevent overwriting all existing users
- [x] replaceNote: Remove
- [x] Add /api to url

Checked lines are added in the linked branch ([68-update-notecontrollerjava](https://github.com/Coppeloons/NoteShare/tree/68-update-notecontrollerjava))
