### ISSUE TITLE
Update UserController.java

### ISSUE THREAD

**Issue by jLereback** [Coppeloons/NoteShare#69]
### Todo:

- [x] addUser: Access for everyone
- [x] getAllUsers: Access for all logged in. Remove ID in result
- [x] getUser: Only admin
- [x] deleteUser: Admin and the user itself
- [x] replaceUser: Remove
- [x] updateUser: Admin and the user utself
- [x] updateUser: Update everything (for now)
- [x] Add /api to url

Checked lines are added in the linked branch ([69-update-usercontrollerjava](https://github.com/Coppeloons/NoteShare/tree/69-update-usercontrollerjava))
