### ISSUE TITLE
Update html

### ISSUE THREAD

**Issue by jLereback** [Coppeloons/NoteShare#73]
### Todo:

- [x]  users: All logged in have access to this one
- [x]  users: userRepo.findAll() when only returning name and username?
- [x]  notes: Admin role to see all notes. Logged in to see all notes with editor role
- [x]  note: Click on the title to go to this endpoint
- [ ] patch: Add multiple users to note
- [ ] patch: Edit note
- [ ] Remove: Delete note
- [x]  noteByUser: Role admin to access all users notes

Checked lines are added in the linked branch ()
